# Categories may be a depth of one. IE. Parent -> Child
# This file should be renamed categories.yaml

Categories:
  - name: Uncategorized
    parent_name:
    match_pattern:
  
  ## Income
  - name: Income
    parent_name:
    match_pattern:

  - name: Salary
    parent_name: Income
    match_pattern:
      - My Job

  - name: Other
    parent_name: Income
    match_pattern:

  ## Utilities
  - name: Utilities
    parent_name: 
    match_pattern:

  - name: Electric
    parent_name: Utilities
    match_pattern:

  - name: Water
    parent_name: Utilities
    match_pattern:

  - name: Internet
    parent_name: Utilities
    match_pattern:

  ## Entertainment
  - name: Entertainment
    parent_name: 
    match_pattern:

  - name: Music
    parent_name: Entertainment
    match_pattern:

  - name: Games
    parent_name: Entertainment
    match_pattern:

  - name: TV
    parent_name: Entertainment
    match_pattern:
      - HULU
      - NETFLIX.COM

  ## Food
  - name: Food
    parent_name:
    match_pattern: 

  - name: Groceries
    parent_name: Food
    match_pattern:
      - Walmart

  - name: Resturants
    parent_name: Food
    match_pattern:
      - TACO BELL
      - MCDONALD'S
      - JACK IN THE BOX

  ## Health
  - name: Health
    parent_name:
    match_pattern:

  - name: Doctor
    parent_name: Health
    match_pattern:
      - Dr. Doc
