# Flask config
TEMPLATES_AUTO_RELOAD: True

LOG:
  LOG_DEBUG_MODE: true
  LOG_PATH: logs/app.log
  ERROR_LOG_PATH: logs/error.log
  LOG_MAX_BYTES: 1000000
  LOG_RETENTION_COUNT: 5
  LOG_FORMAT: '%(asctime)s %(levelname)-7s %(process)d %(request_id)s %(module)s :: %(funcName)s :: %(message)s'

EMAIL:
  ENABLED: false # true/false
  HOST:
  PORT:
  FROM_ADDR: app-no-reply@localhost.com
  ADMIN_EMAIL: # Accepts list
    - user@localhost.com
  NOTIFY_SUBJECT: 
  USERNAME: 
  PASSWORD: 
  SECURE_KEYFILE: # Path to keyfile
  SECURE_CERT: # Path to certificate
  TIMEOUT: # Seconds

DATA:
  TX_IMPORT_PATH: #data/file_import/test_bank_data.csv # CSV data
  CATEGORIES_LIST_PATH: config/categories.yaml # YAML categories config file
  CSV_HEADERS: # Do not change. List of csv headers required for TX_IMPORT_PATH
    - Posting Date
    - Description
    - Amount
    - Type
    - Balance
    
DATABASE:
  HOST: 
  PORT: 
  DB_NAME: financinator
  USERNAME: 
  PASSWORD: 